import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { BRAND_NAME } from "@/config/brand";

export const metadata = {
  title: `Terms — ${BRAND_NAME}`,
};

export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 sm:px-6 lg:px-8 py-12 pt-24">
      <div className="max-w-3xl mx-auto bg-white border border-[var(--color-sand-dark)] rounded-[var(--radius-card)] p-6 sm:p-10 shadow-[var(--shadow-card)]">
        {/* Back Button and Logo Header */}
        <div className="flex items-center justify-between mb-8 pb-4 border-b border-[var(--color-sand-dark)]">
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-3.5 py-2 text-sm font-semibold text-[var(--color-slate)] hover:text-[var(--color-ink)] bg-white border border-[var(--color-sand-dark)] hover:border-[var(--color-gold)] hover:shadow-sm rounded-[var(--radius-button)] transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-gold)]"
          >
            <ArrowLeft className="w-4 h-4 text-[var(--color-gold)]" />
            <span>Back to Home</span>
          </Link>
          <Link
            href="/"
            className="flex flex-col items-end cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-gold)] rounded"
          >
            <span
              className="text-lg font-semibold text-[var(--color-ink)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              {BRAND_NAME}
            </span>
            <span className="w-full h-0.5 bg-[var(--color-gold)] mt-0.5" />
          </Link>
        </div>

        <h1
          className="text-3xl sm:text-4xl font-semibold text-[var(--color-ink)] mb-8"
          style={{ fontFamily: "var(--font-display)" }}
        >
          Terms of Use
        </h1>

        <div className="prose prose-slate max-w-none">
          <p className="text-[var(--color-slate)] mb-6">
            Welcome to {BRAND_NAME}. By using this platform, you agree to these terms.
          </p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              1. Nature of the Service
            </h2>
            <p className="text-[var(--color-slate)]">
              {BRAND_NAME} is a self-reflection tool designed to help individuals explore 
              their readiness for marriage. This is not a clinical assessment, psychological 
              evaluation, or legal advice service. The insights provided are for informational 
              and reflective purposes only.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              2. No Professional Advice
            </h2>
            <p className="text-[var(--color-slate)]">
              The content generated by this platform does not constitute professional advice 
              of any kind. For legal, financial, psychological, or relationship counseling, 
              please consult qualified professionals.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              3. Data Storage
            </h2>
            <p className="text-[var(--color-slate)]">
              All data entered into this platform is stored locally on your device. We do 
              not store your information on our servers. You are responsible for maintaining 
              the security of your device and browser.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              4. Privacy and Consent
            </h2>
            <p className="text-[var(--color-slate)]">
              By using this platform, you consent to the processing of your data as described 
              in our Privacy Policy and Data Consent pages. You may withdraw consent and delete 
              your data at any time.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              5. Limitation of Liability
            </h2>
            <p className="text-[var(--color-slate)]">
              {BRAND_NAME} and its creators shall not be liable for any decisions made or 
              actions taken based on the insights provided by this platform. Use of this 
              service is at your own discretion and risk.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[var(--color-ink)] mb-4">
              6. Changes to Terms
            </h2>
            <p className="text-[var(--color-slate)]">
              We reserve the right to modify these terms at any time. Continued use of the 
              platform after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <p className="text-sm text-[var(--color-stone)] mt-8 pt-8 border-t border-[var(--color-sand-dark)]">
            Last updated: {new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" })}
          </p>
        </div>
      </div>
    </div>
  );
}
